In [1]:
import fitz
import os

def extract_text_from_pdf(pdf_path):
    doc = fitz.open(pdf_path)
    text = ""
    for page in doc:
        text += page.get_text()
    return text

resume_folder = "data/resume/"
resume_texts = []
resume_names = []

for file in os.listdir(resume_folder):
    if file.endswith(".pdf"):
        path = os.path.join(resume_folder, file)
        text = extract_text_from_pdf(path)
        resume_texts.append(text)
        resume_names.append(file)

print("Total resumes:", len(resume_texts))

Total resumes: 58


In [5]:
import fitz

doc = fitz.open("data/resume/Image_1.pdf")
page = doc[0]

print(page.get_text("blocks"))

[]


In [3]:
print("Sample resume text:\n", resume_texts)

Sample resume text:
 ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']


In [6]:
import pytesseract
pytesseract.pytesseract.tesseract_cmd = r"C:\Program Files\Tesseract-OCR\tesseract.exe"

In [ ]:
# from this point onwards, we will use OCR to extract text from the PDF files, as they might be scanned images rather than text-based PDFs.
from pdf2image import convert_from_path
import pytesseract
import os

def extract_text_ocr(pdf_path):
    pages = convert_from_path(pdf_path,poppler_path=r"C:\poppler-25.12.0\Library\bin")
    text = ""
    for page in pages:
        text += pytesseract.image_to_string(page)
    return text

resume_folder = "data/resume/"
resume_texts = []
resume_names = []

for file in os.listdir(resume_folder):
    if file.endswith(".pdf"):
        path = os.path.join(resume_folder, file)
        print("Processing:", file)
        text = extract_text_ocr(path)
        resume_texts.append(text)
        resume_names.append(file)

print("Total resumes extracted:", len(resume_texts))
print("Sample text:\n", resume_texts[0][:500])

Processing: Image_1.pdf
Processing: Image_10.pdf
Processing: Image_11.pdf
Processing: Image_12.pdf
Processing: Image_13.pdf
Processing: Image_14.pdf
Processing: Image_15.pdf
Processing: Image_16.pdf
Processing: Image_17.pdf
Processing: Image_19.pdf
Processing: Image_20.pdf
Processing: Image_21.pdf
Processing: Image_22.pdf
Processing: Image_25.pdf
Processing: Image_26.pdf
Processing: Image_27.pdf
Processing: Image_28.pdf
Processing: Image_29.pdf
Processing: Image_3.pdf
Processing: Image_31.pdf
Processing: Image_34.pdf
Processing: Image_35.pdf
Processing: Image_36.pdf
Processing: Image_39.pdf
Processing: Image_40.pdf
Processing: Image_41.pdf
Processing: Image_43.pdf
Processing: Image_44.pdf
Processing: Image_45.pdf
Processing: Image_47.pdf
Processing: Image_48.pdf
Processing: Image_49.pdf
Processing: Image_5.pdf
Processing: Image_50.pdf
Processing: Image_52.pdf
Processing: Image_53.pdf
Processing: Image_55.pdf
Processing: Image_56.pdf
Processing: Image_6.pdf
Processing: Image_60.pdf
Proc

In [12]:
import json

with open("data/description/job_dataset.json", "r", encoding="utf-8") as f:
    jobs_data = json.load(f)

print(type(jobs_data))
print("Total jobs:", len(jobs_data))
print("Keys in first job:", jobs_data[0].keys())

<class 'list'>
Total jobs: 1068
Keys in first job: dict_keys(['JobID', 'Title', 'ExperienceLevel', 'YearsOfExperience', 'Skills', 'Responsibilities', 'Keywords'])


In [13]:
import json

with open("data/description/job_dataset.json", "r", encoding="utf-8") as f:
    jobs_data = json.load(f)

print(type(jobs_data))         # Should be list
print(type(jobs_data[0]))      # Should be dict
print(len(jobs_data))          # Total jobs

<class 'list'>
<class 'dict'>
1068


In [28]:
for i, job in enumerate(jobs_data):
    if isinstance(job, dict):
        if "Title" not in job:
            print("Missing Title at index:", i)
            print(job)
            break

Missing Title at index: 36
{'JobID': 'AI017', 'ExperienceLevel': 'Senior-Level', 'YearsOfExperience': '5–10 years', 'Skills': ['Python', 'Java', 'C++', 'R', 'Deep Learning', 'NLP', 'Computer Vision', 'Reinforcement Learning', 'LLMs', 'TensorFlow', 'PyTorch', 'Keras', 'Scikit-learn', 'Hugging Face', 'AWS', 'GCP', 'Azure', 'Docker', 'Kubernetes', 'CI/CD', 'Spark', 'Hadoop', 'SHAP', 'LIME'], 'Responsibilities': ['Lead complex AI and ML projects', 'Develop scalable deep learning and NLP pipelines', 'Manage cloud AI infrastructure', 'Mentor junior engineers'], 'Keywords': ['AI', 'ML', 'Senior-Level', 'Deep Learning', 'NLP', 'Cloud', 'MLOps']}


In [27]:
import json

with open("data/description/job_dataset.json", "r", encoding="utf-8") as f:
    jobs_data = json.load(f)
for i, job in enumerate(jobs_data):
    if not isinstance(job, dict):
        print("Not dict at index:", i)
        print(type(job))
        break

In [29]:
# next we will proceed for json text into semantic text

import json

with open("data/description/job_dataset.json", "r", encoding="utf-8") as f:
    jobs_data = json.load(f)

job_texts = []
job_ids = []
job_titles = []

for job in jobs_data:
    print(job.keys())
    combined_text = (
        f"Job Title: {job['Title']}. "
        f"Experience Level: {job['ExperienceLevel']}. "
        f"Years of Experience: {job['YearsOfExperience']}. "
        f"Skills required: {' '.join(job['Skills'])}. "
        f"Responsibilities include: {' '.join(job['Responsibilities'])}. "
        f"Keywords: {' '.join(job['Keywords'])}."
    )
    
    job_texts.append(combined_text)
    job_ids.append(job["JobID"])
    job_titles.append(job["Title"])

print("Total jobs:", len(job_texts))
print("\nSample:\n", job_texts[0][:400])

dict_keys(['JobID', 'Title', 'ExperienceLevel', 'YearsOfExperience', 'Skills', 'Responsibilities', 'Keywords'])
dict_keys(['JobID', 'Title', 'ExperienceLevel', 'YearsOfExperience', 'Skills', 'Responsibilities', 'Keywords'])
dict_keys(['JobID', 'Title', 'ExperienceLevel', 'YearsOfExperience', 'Skills', 'Responsibilities', 'Keywords'])
dict_keys(['JobID', 'Title', 'ExperienceLevel', 'YearsOfExperience', 'Skills', 'Responsibilities', 'Keywords'])
dict_keys(['JobID', 'Title', 'ExperienceLevel', 'YearsOfExperience', 'Skills', 'Responsibilities', 'Keywords'])
dict_keys(['JobID', 'Title', 'ExperienceLevel', 'YearsOfExperience', 'Skills', 'Responsibilities', 'Keywords'])
dict_keys(['JobID', 'Title', 'ExperienceLevel', 'YearsOfExperience', 'Skills', 'Responsibilities', 'Keywords'])
dict_keys(['JobID', 'Title', 'ExperienceLevel', 'YearsOfExperience', 'Skills', 'Responsibilities', 'Keywords'])
dict_keys(['JobID', 'Title', 'ExperienceLevel', 'YearsOfExperience', 'Skills', 'Responsibilities', 'Keyw

In [30]:
import re

def clean_text(text):
    text = re.sub(r"\S+@\S+", "", str(text))
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.lower().strip()

resume_texts = [clean_text(t) for t in resume_texts]
job_texts = [clean_text(t) for t in job_texts]

print("Cleaning done.")
print(resume_texts[0][:300])

Cleaning done.
diana dawa data scientist i q palo alto ca in linkedin com in diana dawa work experience data scientist future energy ltd 06 2018 present palo alto ca develop action plans to mitigate risks in decision making while increasing profitability by leveraging data science drive the interaction and partner


In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

vectorizer = TfidfVectorizer(max_features=5000)

tfidf_resumes = vectorizer.fit_transform(resume_texts)
tfidf_jobs = vectorizer.transform(job_texts)

tfidf_similarity = cosine_similarity(tfidf_resumes, tfidf_jobs)

print("TF-IDF similarity matrix shape:", tfidf_similarity)

TF-IDF similarity matrix shape: [[0.13819513 0.12727529 0.12365094 ... 0.09449938 0.09161009 0.12857135]
 [0.06669755 0.07390272 0.05934978 ... 0.03406046 0.05388851 0.04095037]
 [0.04328455 0.04892278 0.02944002 ... 0.04652028 0.03592104 0.03749438]
 ...
 [0.08157246 0.09406075 0.0844908  ... 0.02303023 0.03255689 0.03705823]
 [0.09736243 0.10695536 0.09640523 ... 0.04513629 0.0562295  0.07034738]
 [0.08530759 0.10227637 0.06351724 ... 0.04210295 0.05300187 0.06659063]]


In [ ]:
# bert embeddings
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

c:\Users\yuvra\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Users\yuvra\AppData\Local\Programs\Python\Python311\Lib\site-packages\huggingface_hub\file_download.py:130: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\yuvra\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to ru

In [35]:
resume_embeddings = model.encode(
    resume_texts,
    convert_to_tensor=True,
    show_progress_bar=True
)

job_embeddings = model.encode(
    job_texts,
    convert_to_tensor=True,
    show_progress_bar=True
)

print("Resume embedding shape:", resume_embeddings.shape)
print("Job embedding shape:", job_embeddings.shape)

Batches: 100%|██████████| 34/34 [00:14<00:00,  2.39it/s]

Resume embedding shape: torch.Size([58, 384])
Job embedding shape: torch.Size([1068, 384])


In [36]:
bert_similarity = cosine_similarity(
    resume_embeddings.cpu().numpy(),
    job_embeddings.cpu().numpy()
)

print("BERT similarity matrix shape:", bert_similarity.shape)

BERT similarity matrix shape: (58, 1068)


In [37]:
import numpy as np

top_indices = np.argmax(bert_similarity, axis=1)

for i in range(5):  # show first 5
    print("Resume:", resume_names[i])
    print("Matched Job ID:", job_ids[top_indices[i]])
    print("Matched Job Title:", job_titles[top_indices[i]])
    print("Similarity Score:", bert_similarity[i][top_indices[i]])
    print("-----")

Resume: Image_1.pdf
Matched Job ID: BA-104
Matched Job Title: Business Analyst
Similarity Score: 0.62605727
-----
Resume: Image_10.pdf
Matched Job ID: MRA-103
Matched Job Title: Market Research Analyst
Similarity Score: 0.6986501
-----
Resume: Image_11.pdf
Matched Job ID: MRA-102
Matched Job Title: Market Research Analyst
Similarity Score: 0.58102036
-----
Resume: Image_12.pdf
Matched Job ID: DA010
Matched Job Title: Data Analyst - Experienced
Similarity Score: 0.7099036
-----
Resume: Image_13.pdf
Matched Job ID: MRA-103
Matched Job Title: Market Research Analyst
Similarity Score: 0.68113995
-----


In [38]:
# ranking metrics
def top_k_accuracy(similarity_matrix, true_indices, k=3):
    top_k = np.argsort(-similarity_matrix, axis=1)[:, :k]
    correct = 0
    for i in range(len(true_indices)):
        if true_indices[i] in top_k[i]:
            correct += 1
    return correct / len(true_indices)

In [39]:
def mean_reciprocal_rank(similarity_matrix, true_indices):
    ranks = []
    sorted_indices = np.argsort(-similarity_matrix, axis=1)
    for i in range(len(true_indices)):
        rank = np.where(sorted_indices[i] == true_indices[i])[0][0] + 1
        ranks.append(1/rank)
    return np.mean(ranks)

In [40]:
top_k_acc = top_k_accuracy(bert_similarity, top_indices, k=3)
mrr = mean_reciprocal_rank(bert_similarity, top_indices)

In [41]:
print(top_k_acc)
print(mrr)

1.0
0.9741379310344828


In [42]:
hybrid_score = 0.7 * bert_similarity + 0.3 * tfidf_similarity
print("Hybrid similarity matrix shape:", hybrid_score.shape)

Hybrid similarity matrix shape: (58, 1068)


In [43]:
# usinf faissl for efficient similarity search
import faiss
dimension = resume_embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(job_embeddings.cpu().numpy())

In [45]:
import numpy as np

top_k = 5
top_k_indices = np.argsort(-bert_similarity, axis=1)[:, :top_k]

In [46]:
resume_index = 0

top5_indices_for_resume = top_k_indices[resume_index]
top5_jobs = [job_texts[i] for i in top5_indices_for_resume]

print("Top 5 candidate jobs selected from BERT:")
for i in top5_indices_for_resume:
    print(job_ids[i], "-", job_titles[i])

Top 5 candidate jobs selected from BERT:
BA-104 - Business Analyst
BA-103 - Business Analyst
BA-120 - Business Analyst
BA-116 - Business Analyst
BA-108 - Business Analyst


In [48]:
# cross encoder for fine grained re-ranking
from sentence_transformers import CrossEncoder

cross_encoder = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-6-v2")

resume_text = resume_texts[resume_index]
pairs = [(resume_text, job_text) for job_text in top5_jobs]
scores = cross_encoder.predict(pairs)

Loading weights: 100%|██████████| 105/105 [00:00<00:00, 937.20it/s, Materializing param=classifier.weight]                                    
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-6-v2
Key                          | Status     |  | 
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


In [49]:
# re-ranking using cross encoder scores
reranked = list(zip(top5_indices_for_resume, scores))
reranked.sort(key=lambda x: x[1], reverse=True)

print("\nAfter Cross-Encoder Reranking:\n")

for idx, score in reranked:
    print("Job:", job_ids[idx], "-", job_titles[idx])
    print("Score:", score)
    print("------")


After Cross-Encoder Reranking:

Job: BA-104 - Business Analyst
Score: -8.107508
------
Job: BA-103 - Business Analyst
Score: -8.200491
------
Job: BA-108 - Business Analyst
Score: -8.230487
------
Job: BA-120 - Business Analyst
Score: -8.244972
------
Job: BA-116 - Business Analyst
Score: -8.244972
------


In [50]:
job_embeddings = model.encode(job_texts)
np.save("job_embeddings.npy", job_embeddings)